An error occurred while executing the following cell:
------------------
!pip install -q causalgraphicalmodels
!pip install -q pgmpy
!pip install superimport

!wget -q https://raw.githubusercontent.com/probml/pyprobml/master/scripts/pyprobml_utils.py
!wget -q https://raw.githubusercontent.com/probml/pyprobml/master/scripts/pgmpy_utils.py
# import probml_utils as pml
try:
    import pgmpy_utils as pgm
except ModuleNotFoundError:
    %pip install pgmpy_utils
    import pgmpy_utils as pgm
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_4736/3589137354.py in <module>
      8 try:
----> 9     import pgmpy_utils as pgm
     10 except ModuleNotFoundError:

ModuleNotFoundError: No module named 'pgmpy_utils'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_4736/3589137354.py in <module>
     10 except ModuleNotFoundError:
     11     get_ipython().run_line_magic('pip', 'install pgmpy_utils')
---> 12     import pgmpy_utils as pgm

ModuleNotFoundError: No module named 'pgmpy_utils'
ModuleNotFoundError: No module named 'pgmpy_utils'
